title: Introduction to Software Development Tooling
description: "Learn the command line, version control, build systems, and correctness in NEU's CS 4973: ISDT."
theme: jekyll-theme-primer
google_analytics: UA-26440738-1
url: 'https://bernsteinbear.com'
baseurl: /isdt
permalink: pretty
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - gensched.py
